import './globals.css'

import Header from './header'
import Footer from './footer'

export const metadata = {
  title: 'Clark Pegg',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) =>
  (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )

export default RootLayout
